
typedef struct {
	char* name;
	float hp;
	int speed;
	float hp_steal;
	float phy_crit;
	float sp_crit;
	float potency;
	float tenacity;
	int numActiveAbility;
	char* ability[5];
	float min_damage[5];
	float max_damage[5];
	int cooldown[5];
} Hero;
extern Hero* ROSTER[77];
extern Hero AAYLA_SECURA;
extern Hero ADMIRAL_ACKBAR;
extern Hero AHSOKA_TANO;
extern Hero ASAJJ_VENTRESS;
extern Hero BARRISS_OFFEE;
extern Hero BIGGS_DARKLIGHTER;
extern Hero BOBA_FETT;
extern Hero CAD_BANE;
extern Hero CAPTAIN_PHASMA;
extern Hero CHIEF_CHIRPA;
extern Hero CLONE_SERGEANT_PHASE_I;
extern Hero CLONE_WARS_CHEWBACCA;
extern Hero CORUSCANT_UNDERWORLD_POLICE;
extern Hero COUNT_DOOKU;
extern Hero CT_5555_FIVES;
extern Hero CT_7567_REX;
extern Hero DARTH_MAUL;
extern Hero DARTH_SIDIOUS;
extern Hero DARTH_VADER;
extern Hero DATHCHA;
extern Hero EETH_KOTH;
extern Hero EWOK_ELDER;
extern Hero EWOK_SCOUT;
extern Hero FINN;
extern Hero FO_OFFICER;
extern Hero FO_STORMTR;
extern Hero FO_TIE_PILOT;
extern Hero GENERAL_GRIEVOUS;
extern Hero GENERAL_VEERS;
extern Hero GEONOSIAN_SOLDIER;
extern Hero GRAND_MASTER_YODA;
extern Hero GRAND_MOFF_TARKIN;
extern Hero GREEDO;
extern Hero HK_47;
extern Hero HR_SCOUT;
extern Hero HR_SOLDIER;
extern Hero IG_100_MAGNAGUARD;
extern Hero IG_86_SENTINEL_DROID;
extern Hero IG_88;
extern Hero IMA_GUN_DI;
extern Hero JAWA;
extern Hero JEDI_CONSULAR;
extern Hero JK_ANAKIN;
extern Hero JK_GUARDIAN;
extern Hero KIT_FISTO;
extern Hero KYLO_REN;
extern Hero LANDO_CALRISSIAN;
extern Hero LOBOT;
extern Hero LUKE_SKYWALKER;
extern Hero LUMINARA_UNDULI;
extern Hero MACE_WINDU;
extern Hero MAGMATROOPER;
extern Hero MOB_ENFORCER;
extern Hero NS_ACOLYTE;
extern Hero NS_INITIATE;
extern Hero NUTE_GUNRAY;
extern Hero OBI_WAN_KENOBI_OLD_BEN;
extern Hero OLD_DAKA;
extern Hero PLO_KOON;
extern Hero POE_DAMERON;
extern Hero POGGLE_THE_LESSER;
extern Hero PRINCESS_LEIA;
extern Hero QUI_GON_JINN;
extern Hero RES_PILOT;
extern Hero RES_TROOPER;
extern Hero REY;
extern Hero ROYAL_GUARD;
extern Hero SAVAGE_OPRESS;
extern Hero SNOWTROOPER;
extern Hero STORMTR;
extern Hero STORMTR_HAN;
extern Hero TALIA;
extern Hero TEEBO;
extern Hero TUSKEN_RAIDER;
extern Hero TUSKEN_SHAMAN;
extern Hero UGNAUGHT;
extern Hero URORRURRR;
